from enum import IntEnum,Enum
class ModuleStates(IntEnum):
    MODULE_EMPTY=0
    MODULE_LOADED=1
    MODULE_CATCHING=2
    MODULE_UNRECOGNIZE_ONCETIME=3
    MODULE_UNRECOGNIZE_TWICETIME=4
    MODULE_ERROR=5
    MODULE_ULTRASONIC=6
    MODULE_ULTRA1_UNRECOGNIZED=7
    MODULE_ULTRA2_UNRECOGNIZED=8
    MODULE_ULTRA1_CAUGHT=9

class RobotStates(IntEnum):
    ROBOT_WAITING=2
    ROBOT_OFFLINE=0
    ROBOT_CATCHED=4
    ROBOT_ACK_CATCHED_ERROR=7
    ROBOT_ACK_CATCHED=9
    ROBOT_RECOGNIZE_ERROR=10
    ROBOT_CONNECTED=11
    ROBOT_DROP_PASS=12
    ROBOT_CLEARING=13
    ULTRASONIC_ROBOT1_UNRECOGNIZED=1
    ULTRASONIC_ROBOT2_UNRECOGNIZED=3
    ULTRASONIC_ROBOT2_INSERTED=6
    ULTRA_ROBOT_ACK_INSERT_CATCH=14
    ULTRA_ROBOT_ACK_INSERT=15
    ULTRA_ROBOT_ACK_CATCH=16
    ULTRA_ROBOT_ACK_CATCH_ERROR=17
    ULTRA_ROBOT_ACK_INSERT_ERROR=18
    ULTRA_ROBOT_ACK_CATCH_INSERT_ERROR=19
    ULTRA_ROBOT_WORKING=20
    ULTRASONIC_ROBOT1_INSERT_ERROR=21
    ULTRASONIC_ROBOT2_INSERTED_WAIT=22





